### ISSUE TITLE
Recenzja

### ISSUE THREAD

**Issue by Nowosad** [spacea/projekt2024-zbaszyniak#1]
Plik README podoba mi się -- zawiera najważniejsze informacje w uporządkowanej formie. Aplikacja także działa bardzo sprawnie i wygląda dobrze.

Do zmiany:

- W pliku README, przy sekcji "Niezbędne pakiety" kod zawiera niepotrzebne spacje:   install.package ("shiny") ->   install.package("shiny"); tutaj jest też literówka, bo funkcja nazywa się install.packages (s na końcu). Ten kod można też uprościć jako "`install.packages(c("shiny", "semantic.dashboard", "plotly", "DT"))`"
- W pliku README jest kilka literówek do poprawy, np. "dokumnetujący"
- Coś jest nie tak z "Take a look at datatable" (na marginesie, przemianowałbym to na "Take a look at the data") -- pokazuje tylko informacje o osobach z danej daty, a nie z całej bazy (tak jak mapa wyzej)

Sugestie:

- Moim zdaniem dobrym ulepszeniem aplikacji byłoby dodanie możliwości wybrania danej osoby i uzyskania konkretnych informacji o niej (idealnie ze zdjęciem, ale rozumiem, że to może być już za dużo)
- Pliki w repozytorium można zorganizować w podfoldery, np. podfolder "data" zawierający dane, czy podfolder "R" zawierający kod przygotowujący dane
- Może warto w README przenieść sekcję "Niezbędne pakiety" wyżej (przed uruchomieniem projektu)? W tym momencie próbowałem uruchomić projekt, ale dostałem komunikat, że nie mam pakietów.
- W sekcji "Pobieranie repozytorium" można usunąć nowe linie między kolejnymi wypunktowaniami, da to lepszy wizualnie efekt
- Sekcja "Autorzy (a bardziej autorki)" może nazywać się "Autorki"
- W jaki sposób sortowane są nazwiska w sekcji "People born on this date"? Czy można to ulepszyć poprzez sortowanie wg. najbardziej znanej osoby lub coś podobnego?

[90/100]

**Comment by marzba19** [comment]
## Poprawiłyśmy wszystko z kategorii do zmiany. 
## Z kategorii sugestie:
- dodałyśmy linki do Wikipedii o danych osobach, przez co możliwe jest rozszerzenie wiedzy o nich
- dane znajdują się teraz w folderze "data"
- dokonałyśmy zasugerowanych zmian w readme
- dane już wcześniej były sortowane wg kolumny "popularity", która ma być wskaźnikiem popularności
